server:
  port: 8081
spring:
  application:
    name: PRODUCT-SERVICE
  datasource:
    url: jdbc:oracle:thin:@192.168.55.2:1521/ORCL21PDB1
    username: MYUSER
    password: ${DB_PASSWORD:12345}  # D?ng bi?n m?i tr??ng, m?c ??nh l? 12345
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update  # C? th? ??i th?nh validate n?u kh?ng mu?n t? ??ng s?a DB
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # Hi?n th? SQL r? r?ng h?n trong log

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defauldZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG